
project_id = "dqaihawavxlacegykwqu"

[functions]
[functions.test-connection]
verify_jwt = false
[functions.test-delay]
verify_jwt = false
[functions.generate-question]
verify_jwt = false
[functions.generate-explanation]
verify_jwt = false

