
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwpfdtthhqsevqctfuiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13cGZkdHRoaHFzZXZxY3RmdWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwODcxMTUsImV4cCI6MjA1NTY2MzExNX0.ln--N66DNi4BdjpfqoEvA7EikvH3EaQLPLCuXeKFNWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
