// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

// Get the environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

console.log('Initializing Supabase client with:', {
  url: supabaseUrl,
  hasKey: !!supabaseAnonKey,
  env: import.meta.env.MODE
});

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Missing Supabase environment variables:', {
    url: supabaseUrl,
    hasKey: !!supabaseAnonKey
  });
  throw new Error('Missing Supabase environment variables');
}

const options = {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storageKey: 'iqify_auth',
    storage: window.localStorage,
    flowType: 'implicit' as const
  },
  global: {
    headers: { 
      'x-application-name': 'brain-training-app',
      'x-client-info': 'supabase-js-web'
    },
  }
};

// Create the Supabase client with explicit URL
export const supabase = createClient<Database>(
  supabaseUrl,
  supabaseAnonKey,
  options
);

// Add connection status check
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Auth state changed:', event, 'Session:', session ? 'exists' : 'none');
});
